#!/usr/bin/env bash
# One-command local dev setup for Attic.
# Usage: ./scripts/dev-setup.sh
#
# Prerequisites:
#   - Local Supabase running (supabase start)
#   - Python 3.12+ with uv installed
#   - Node.js 18+ with npm
#
# What this does:
#   1. Creates backend .env with local Supabase defaults
#   2. Creates frontend .env.local with local Supabase defaults
#   3. Installs backend + frontend deps
#   4. Runs DB migrations
#   5. Seeds test data (user + 10 media_events with embeddings)

set -euo pipefail
cd "$(dirname "$0")/.."
ROOT=$(pwd)

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info() { echo -e "${GREEN}[setup]${NC} $1"; }
warn() { echo -e "${YELLOW}[setup]${NC} $1"; }
fail() { echo -e "${RED}[setup]${NC} $1"; exit 1; }

# ---------- Check prerequisites ----------

info "Checking prerequisites..."

command -v supabase >/dev/null 2>&1 || fail "supabase CLI not found. Install: brew install supabase/tap/supabase"
command -v uv >/dev/null 2>&1 || fail "uv not found. Install: curl -LsSf https://astral.sh/uv/install.sh | sh"
command -v node >/dev/null 2>&1 || fail "node not found. Install Node.js 18+"

# Check if local Supabase is running
if ! docker ps --format '{{.Names}}' 2>/dev/null | grep -q supabase_db; then
    warn "Local Supabase not running. Starting it..."
    FOUND_SB=false
    for candidate in "$HOME/Dev/attic" "$ROOT" "$ROOT/.."; do
        if [ -d "$candidate/supabase" ]; then
            (cd "$candidate" && supabase start)
            FOUND_SB=true
            break
        fi
    done
    if [ "$FOUND_SB" = false ]; then
        fail "Can't find supabase project. Run 'supabase start' from your project root first."
    fi
fi

# ---------- Get local Supabase keys ----------

info "Getting local Supabase keys..."

# Find the supabase project directory (check common locations)
SUPABASE_DIR=""
for candidate in "$HOME/Dev/attic" "$ROOT" "$ROOT/.."; do
    if [ -d "$candidate/supabase" ]; then
        SUPABASE_DIR="$candidate"
        break
    fi
done

if [ -n "$SUPABASE_DIR" ]; then
    SUPABASE_STATUS=$(cd "$SUPABASE_DIR" && supabase status 2>&1)
else
    SUPABASE_STATUS=$(supabase status 2>&1)
fi

SUPABASE_URL="http://127.0.0.1:54321"
DB_URL="postgresql+asyncpg://postgres:postgres@127.0.0.1:54322/postgres"

# Extract publishable key (grep for the sb_ prefix keys directly)
PUBLISHABLE_KEY=$(echo "$SUPABASE_STATUS" | grep -o 'sb_publishable_[A-Za-z0-9_-]*')
SECRET_KEY=$(echo "$SUPABASE_STATUS" | grep -o 'sb_secret_[A-Za-z0-9_-]*')

if [ -z "$PUBLISHABLE_KEY" ] || [ -z "$SECRET_KEY" ]; then
    fail "Could not extract Supabase keys. Is local Supabase running?"
fi

info "Supabase URL: $SUPABASE_URL"
info "Publishable key: ${PUBLISHABLE_KEY:0:20}..."

# ---------- Backend .env ----------

BACKEND_ENV="$ROOT/src/backend/.env"
if [ -f "$BACKEND_ENV" ]; then
    info "Backend .env already exists, checking for missing keys..."
else
    info "Creating backend .env..."
fi

# Check if we can copy API keys from the Dev/attic .env
DEV_ENV="$HOME/Dev/attic/src/backend/.env"
ANTHROPIC_KEY=""
GEMINI_KEY=""
OPENAI_KEY=""
APIFY_KEY=""

if [ -f "$DEV_ENV" ]; then
    ANTHROPIC_KEY=$(grep "^ANTHROPIC_API_KEY=" "$DEV_ENV" | cut -d= -f2- | tr -d '"')
    GEMINI_KEY=$(grep "^GEMINI_API_KEY=" "$DEV_ENV" | cut -d= -f2- | tr -d '"')
    OPENAI_KEY=$(grep "^OPENAI_API_KEY=" "$DEV_ENV" | cut -d= -f2- | tr -d '"')
    APIFY_KEY=$(grep "^APIFY_API_TOKEN=" "$DEV_ENV" | cut -d= -f2- | tr -d '"')
    info "Copied API keys from existing .env"
fi

if [ ! -f "$BACKEND_ENV" ]; then
    cat > "$BACKEND_ENV" <<EOF
# Auto-generated by scripts/dev-setup.sh
# Local Supabase config
DATABASE_URL=$DB_URL
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SECRET_KEY=$SECRET_KEY
SUPABASE_JWT_SECRET=super-secret-jwt-token-with-at-least-32-characters-long
USE_LOCAL_SUPABASE=true

# Third-party APIs
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
GEMINI_API_KEY=$GEMINI_KEY
OPENAI_API_KEY=$OPENAI_KEY
APIFY_API_TOKEN=$APIFY_KEY

# AWS (populate with real keys for pipeline testing)
AWS_ACCESS_KEY_ID=placeholder
AWS_SECRET_ACCESS_KEY=placeholder
AWS_REGION=us-east-1
SQS_QUEUE_URL=

# Application
ENVIRONMENT=development
LOG_LEVEL=INFO
CORS_ORIGINS=["http://localhost:3000"]
EOF
    info "Created $BACKEND_ENV"
fi

# ---------- Frontend .env.local ----------

FRONTEND_ENV="$ROOT/src/frontend/.env.local"
if [ ! -f "$FRONTEND_ENV" ]; then
    cat > "$FRONTEND_ENV" <<EOF
NEXT_PUBLIC_SUPABASE_URL=$SUPABASE_URL
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$PUBLISHABLE_KEY
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_ENVIRONMENT=development
NEXT_PUBLIC_POSTHOG_KEY=
NEXT_PUBLIC_POSTHOG_HOST=
EOF
    info "Created $FRONTEND_ENV"
else
    info "Frontend .env.local already exists"
fi

# ---------- Install dependencies ----------

info "Installing backend dependencies..."
(cd "$ROOT/src/backend" && uv sync --all-extras --quiet)

info "Installing frontend dependencies..."
(cd "$ROOT/src/frontend" && npm install --silent 2>/dev/null)

# ---------- Run migrations ----------

info "Running database migrations..."
(cd "$ROOT/src/backend" && uv run alembic upgrade head 2>&1) || warn "Migrations may have already been applied"

# ---------- Seed test data ----------

info "Seeding test data..."
if [ -z "$OPENAI_KEY" ]; then
    warn "No OPENAI_API_KEY found — skipping seed (embeddings need OpenAI). Run manually:"
    warn "  cd src/backend && uv run python ../../scripts/seed_local.py"
else
    (cd "$ROOT/src/backend" && \
        DATABASE_URL="$DB_URL" OPENAI_API_KEY="$OPENAI_KEY" \
        uv run python "$ROOT/scripts/seed_local.py" 2>&1) || warn "Seed may have already been run"
fi

# ---------- Done ----------

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}  Local dev environment ready!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Start the backend:"
echo "  cd src/backend && uv run uvicorn app.main:app --reload"
echo ""
echo "Start the frontend (separate terminal):"
echo "  cd src/frontend && npm run dev"
echo ""
echo "Then open: http://localhost:3000"
echo ""
echo "Login credentials: test@attic.dev / testtest123"
echo "  - 10 pre-loaded media_events (7 restaurant, 3 other)"
echo "  - Sign in with email/password on the login page"
echo "  - Try asking: 'pull all the restaurants ive liked'"
echo ""
