#!/usr/bin/env bash
set -eo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MASTER="$REPO_ROOT/.env.master"

if [[ ! -f "$MASTER" ]]; then
  echo "ERROR: .env.master not found at $MASTER"
  echo "  Copy .env.master.example to .env.master and fill in your keys:"
  echo "  cp .env.master.example .env.master"
  exit 1
fi

echo "Generating env files from .env.master..."

# --- Backend: copy master + append backend-specific vars ---
cp "$MASTER" "$REPO_ROOT/src/backend/.env"
cat >> "$REPO_ROOT/src/backend/.env" <<'EOF'

# --- Backend-specific (appended by setup-env.sh) ---
BACKEND_PORT=8000
CORS_ORIGINS=["http://localhost:3000"]
EOF
echo "  ✓ src/backend/.env"

# --- Frontend: extract and prefix vars for Next.js ---
# Source master to get variable values
set -a
source "$MASTER"
set +a

cat > "$REPO_ROOT/src/frontend/.env.local" <<EOF
# Generated by scripts/setup-env.sh — do not edit directly
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY}
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_ENVIRONMENT=${ENVIRONMENT:-development}
NEXT_PUBLIC_POSTHOG_KEY=${POSTHOG_API_KEY:-}
NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN:-}
EOF
echo "  ✓ src/frontend/.env.local"

# --- Workbench: AI keys only ---
cat > "$REPO_ROOT/workbench/.env" <<EOF
# Generated by scripts/setup-env.sh — do not edit directly
GEMINI_API_KEY=${GEMINI_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
APIFY_API_TOKEN=${APIFY_API_TOKEN}
EOF
echo "  ✓ workbench/.env"

echo "Done. All env files generated from .env.master."
